
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: "fyrno/foodgram_backend"
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/backend_media
    depends_on:
      - db

    frontend:
      image: "fyrno/foodgram_frontend"
      env_file: .env
      volumes:
        - static:/frontend_static

    nginx:
      image: "fyrno/foodgram_nginx"
      env_file: .env
      volumes:
        - static:/backend_static
        - media:/backend_media
      ports:
        - 80:80
      depends_on:
        - backend
        - frontend
