# Generated by Django 3.2.20 on 2025-01-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
