# Generated by Django 3.2.20 on 2025-01-15 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250115_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может бытьменьше 1 минуты.'), django.core.validators.MaxValueValidator(1440, message='Время приготовления не можетпревышать 1440 минут.')], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
