# Generated by Django 3.2.20 on 2025-01-14 10:11

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250114_0041'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodgramuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Никнейм может содержать только буквы, цифры и символы @ . + - _', regex='^[\\w.@+-]+\\Z')], verbose_name='Никнейм'),
        ),
    ]
